name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: actions/setup-node@v3

    - name: Build
      run: npm install && npm run clean && npm run build

    - name: Install AWS CLI
      run: |
        pip install awscli

    - name: Deploy to S3
      run: |
        aws s3 sync ./dist s3://${{ secrets.AWS_S3_BUCKET }} --delete
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    # - name: Invalidate CloudFront Cache
    #   if: ${{ always() }}
    #   uses: chetan/invalidate-cloudfront-action@v1
    #   with:
    #     distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
    #     paths: '/*'
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  